#!/usr/bin/env python3
"""
UGC Factory - Keyframe Video Interpolation

Takes start + peak keyframe images generated by test_images.py and uses
Veo 3.1 first-frame + last-frame interpolation to generate smooth video.

Usage:
    python test_video.py              # Run all actions
    python test_video.py crying       # Run single action
"""

import json
import os
import sys
import time
from pathlib import Path

from dotenv import load_dotenv
from google import genai
from google.genai import types
import mimetypes

load_dotenv()

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

OUTPUT_DIR = Path("test_outputs")
CONFIG_PATH = Path("avatar_config.json")
VIDEO_MODEL = "veo-3.1-generate-preview"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def load_config() -> dict:
    """Load the avatar configuration JSON."""
    with open(CONFIG_PATH) as f:
        return json.load(f)


def load_image(path: Path) -> types.Image:
    """Load a saved image as a genai Image from raw bytes."""
    mime_type = mimetypes.guess_type(str(path))[0] or "image/png"
    image_bytes = path.read_bytes()
    return types.Image(image_bytes=image_bytes, mime_type=mime_type)


def generate_video(
    client: genai.Client,
    start_image: types.Image,
    peak_image: types.Image,
    prompt: str,
    save_path: Path,
) -> None:
    """Generate a video with Veo 3.1 using first-frame + last-frame interpolation."""
    print(f"  Generating video: {save_path.name} ...")
    print("    (this may take a few minutes)")

    operation = client.models.generate_videos(
        model=VIDEO_MODEL,
        prompt=prompt,
        image=start_image,
        config=types.GenerateVideosConfig(
            aspect_ratio="9:16",
            resolution="1080p",
            duration_seconds="8",
            person_generation="allow_adult",
            last_frame=peak_image,
        ),
    )

    while not operation.done:
        print("    Waiting for video generation...")
        time.sleep(10)
        operation = client.operations.get(operation)

    generated_video = operation.response.generated_videos[0]
    client.files.download(file=generated_video.video)
    generated_video.video.save(str(save_path))
    print(f"    Saved: {save_path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def run_action(client: genai.Client, config: dict, action: str) -> None:
    """Generate interpolated video for one action from its keyframes."""
    action_dir = OUTPUT_DIR / action
    action_cfg = config["actions"][action]

    start_path = action_dir / f"{action}_frame_start.png"
    peak_path = action_dir / f"{action}_frame_peak.png"

    for p in [start_path, peak_path]:
        if not p.exists():
            print(f"Error: Missing keyframe {p}")
            print("Run test_images.py first to generate keyframes.")
            sys.exit(1)

    print(f"\n{'='*60}")
    print(f"Action: {action}")
    print(f"{'='*60}")

    print("\n  Loading keyframe images...")
    start_image = load_image(start_path)
    peak_image = load_image(peak_path)

    prompt = action_cfg["video_prompt"]
    print(f"  Video prompt: {prompt[:80]}...")

    print("\n  Generating Veo 3.1 interpolated video...")
    video_path = action_dir / f"{action}_video.mp4"
    generate_video(
        client,
        start_image=start_image,
        peak_image=peak_image,
        prompt=prompt,
        save_path=video_path,
    )

    print(f"\n  Done! Video saved: {video_path}")
    print(f"  Review checklist:")
    print(f"    - Does the motion from start to peak look natural?")
    print(f"    - Is the character consistent throughout?")
    print(f"    - Is clothing and background preserved?")
    print(f"    - Does the '{action}' transition feel smooth?")


def main():
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        print("Error: GOOGLE_API_KEY environment variable is not set.")
        print("Set it with: export GOOGLE_API_KEY='your-key'")
        print("Or create a .env file (see .env.example)")
        sys.exit(1)

    client = genai.Client(api_key=api_key)
    config = load_config()
    available_actions = list(config["actions"].keys())

    if len(sys.argv) > 1:
        action = sys.argv[1]
        if action not in available_actions:
            print(f"Error: Unknown action '{action}'")
            print(f"Available: {', '.join(available_actions)}")
            sys.exit(1)
        actions_to_run = [action]
    else:
        actions_to_run = available_actions

    print(f"Generating videos for: {', '.join(actions_to_run)}")
    print(f"Output: {OUTPUT_DIR.resolve()}")

    for action in actions_to_run:
        run_action(client, config, action)

    print(f"\n{'='*60}")
    print("Video generation complete!")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
